version: '3.9'

services:
  # ... (seal-ui, e2e-runner services are unchanged)

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    # ...
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5   
   
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # ✨ Kibana will now use the token for authentication ✨
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN_FILE=/usr/share/kibana/tokens/kibana-token.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 5
     depends_on:
      master-setup:
        condition: service_completed_successfully

   master-setup:
    container_name: master-setup
    build:
      context: ./setup # Assumes script and Dockerfile are in a 'setup' folder
      dockerfile: Dockerfile
    networks:
      - monitoring-net
    # It waits for both ES and Kibana to start listening before it runs.
   depends_on:
      elasticsearch:
        condition: service_healthy

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.12.2
    container_name: apm-server
    # ... (environment variables are the same)
    networks:
      - monitoring-net
    # This service waits for the one-off setup container to complete successfully
    depends_on:
      kibana-setup:
        condition: service_completed_successfully

# ... (networks, volumes)